name: Weather Logger Go

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - run: go run fetch_api.go

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - run: |
          git add weather_data.csv
          git diff --cached --quiet || git commit -m "Update weather data at $(date -u)"
          git push
